### ISSUE TITLE
`multiple-choice` also supports inline choices instead of lists

### ISSUE THREAD

**Issue by mmcknett** [cyvaer-llc/learn-viewer#23]
**Describe the bug**
Challenge `e199a18d-973e-42ce-aee6-c85ecbfc1e75` in [Intro to Dev Environment](https://github.com/Ada-Developers-Academy/core-unit-1/blob/main/intro-to-dev-environment/problem-set-intro-to-dev-environment.md) has `options` listed inline, separated by `|`s.

> a| `python3 --version` b| `python3 command-line.py` c| `cd python3` d| `python3`

The answer is a single item, too:

> d|

We assumed these would always be lists when implementing `multiple-choice`, so this breaks the implementation.

**To Reproduce**
1. Go to [Intro to Dev Environment (on localhost)](http://localhost:5173/?course=https%3A%2F%2Fraw.githubusercontent.com%2FAda-Developers-Academy%2Fcore%2Fmain%2Fcourse.yaml&section=Unit+1&standard=QkZshi&content-file-uid=ac57c0c7-1465-45ab-bd13-be8764bde949)
4. See "Markdown failed to load" and error in console:
```
Uncaught Error: Expected a single list
    at getList (make-option.ts:44:11)
    at extractOptionsNodesAndData (make-option.ts:17:23)
    at visitor (index.ts:37:51)
    at overload (index.js:173:16)
    at node (heading) (index.js:189:31)
    at node (root) (index.js:206:78)
    at visitParents (index.js:148:34)
    at visit (index.js:165:7)
    at transformer (index.ts:194:5)
    at wrapped (index.js:115:27)
```

**Expected behavior**
The choices should be listed as check boxes, just like other instances of a `multiple-choice`. The answer should be checkable. (So in this case, selecting `d` and checking should result in a "Correct" message.)

**Comment by mmcknett** [comment]
This issue is addressed with #26

**Comment by mmcknett** [comment]
The issue isn’t fully resolved, actually. It no longer crashes, but the markdown blocks that include code end up being absent. The fix assumes that there is no markdown present in the answer options.

With the #26 fix, here’s what renders in this example:

![](https://github.com/user-attachments/assets/cf0b131e-d6ef-45eb-a251-03831c7c236d)
