### ISSUE TITLE
Crash in option ID parsing

### ISSUE THREAD

**Issue by mmcknett** [cyvaer-llc/learn-viewer#7]
**Describe the bug**
Crash when loading a particular markdown file:

```
challenge-reducer.ts:67
Uncaught TypeError: Cannot read properties of undefined (reading 'split')
    at challengeIdFromOptionId (challenge-reducer.ts:67:37)
    at Object.isSelected (challenge-reducer.ts:225:29)
    at Checkbox (checkbox.tsx:14:49)
    at renderWithHooks (react-dom.development.js:16305:18)
    at mountIndeterminateComponent (react-dom.development.js:20074:13)
    at beginWork (react-dom.development.js:21587:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
```

**To Reproduce**
1. `npm run dev` the app locally
1. Go to http://localhost:5173/?course=https%3A%2F%2Fraw.githubusercontent.com%2FAda-Developers-Academy%2Fcore%2Fmain%2Fcourse.yaml&section=Unit+2&standard=3211fc3d75369f96b537a4535fcbba6d&content-file-uid=1ccd31d7b789d74e78d94c236193bb8d
1. See error

**Expected behavior**
The lesson "Activity: Intro to SQL" should load

**Comment by rishikush31** [comment]
Hey i can work on the issue  , can you assign it to me..

**Comment by mmcknett** [comment]
Hi Rishi, great to meet you! Thanks for offering to take this issue. I've assigned it to you. Please let me know here if you run into any issues debugging, or if you need any context. So far I have been the only one reading/writing/reviewing this code, so it is likely to have parts that are hard for someone else to understand. 😅

**Comment by mmcknett** [comment]
Addressed with https://github.com/cyvaer-llc/learn-viewer/pull/28
